
const languages = {
    title: {
        english: 'Bookshop ERP',
        hebrew: 'מערכת מכירת ספרים',
        french: 'ERP de la boutique de livres',
        spanish: 'ERP de la tienda de libros',
        italian: 'ERP della negoziazione libri',
        german: 'ERP der Buchhändler',
    },

    updateBook: {
        english: 'Update Book',
        hebrew: 'עדכון ספר',
        french: 'Modifier un livre',
        spanish: 'Actualizar libro',
        italian: 'Aggiorna libro',
        german: 'Buch aktualisieren',
        russian: 'Обновить книгу',
    },
    thId:{
        english: 'ID',
        hebrew: 'מספר זהות',
        french: 'ID',
        spanish: 'ID',
        italian: 'ID',
        german: 'ID',
        russian: 'ID',
    },
    thTitle:{
        english: 'Title',
        hebrew: 'כותרת',
        french: 'Titre',
        spanish: 'Título',
        italian: 'Titolo',
        german: 'Titel',
        russian: 'Название',
    },
    thPrice:{
        english: 'Price',
        hebrew: 'מחיר',
        french: 'Prix',
        spanish: 'Precio',
        italian: 'Prezzo',
        german: 'Preis',
        russian: '��ена',
    },
    thDelete:{
        english: 'Delete',
        hebrew: 'מחיר',
        french: 'Supprimer',
        spanish: 'Borrar',
        italian: 'Cancella',
        german: 'Löschen',
        russian: 'Удалить',
    },
    thUpdate:{
        english: 'Update',
        hebrew: 'עדכון',
        french: 'Modifier',
        spanish: 'Actualizar',
        italian: 'Aggiorna',
        german: 'Aktualisieren',
        russian: 'Обновить',
    },
    deleteButton:{
        english: 'Delete',
        hebrew: 'מחיקה',
        french: 'Supprimer',
        spanish: 'Borrar',
        italian: 'Cancella',
        german: 'Löschen',
        russian: 'Удалить',
    },
    updateButton:{
        english: 'Update Book',
        hebrew: 'עדכון ספר',
        french: 'Modifier un livre',
        spanish: 'Actualizar libro',
        italian: 'Aggiorna libro',
        german: 'Buch aktualisieren',
        russian: 'Обновить книгу',
    },
    newBook:{
        english: 'Add New Book',
        hebrew: 'הוספת ספר חדש',
        french: 'Ajouter un nouveau livre',
        spanish: 'Añadir nuevo libro',
        italian: 'Aggiungi un nuovo libro',
        german: 'Neuen Buch hinzufügen',
        russian: 'Добавить новую книгу',
    },
    loadData:{
        english: 'Load Data',
        hebrew: 'אתחול נתונים',
        french: 'Charger les données',
        spanish: 'Cargar datos',
        italian: 'Carica i dati',
        german: 'Daten laden',
        russian: 'Загрузить данные',
    },
    updateBookTitle: {
        english: 'Update Book',
        hebrew: 'עדכו�� ��פר',
        french: 'Modifier un livre',
        spanish: 'Actualizar libro',
        italian: 'Aggiorna libro',
        german: 'Buch aktualisieren',
        russian: 'Обновить книгу',
    }
}